local_backend: true

#logo_url: /logo.svg

backend:
  name: 'github'
  repo: vishalscodes/shashiks
  branch: main
  automatic_deployments: false
  base_url: https://sveltia-cms-auth.vishsandy410.workers.dev

media_folder: 'public/images/blog'
public_folder: '/images/blog'

#i18n:
#  structure: 'multiple_folders'
#  locales: ['en', 'it']
#  default_locale: 'en'

collections:
  - name: 'posts'
    #i18n: true
    label: 'Blog Posts'
    folder: 'src/content/blog'
    create: true
    delete: true
    fields:
      - name: 'title'
        widget: 'string'
        label: 'Post Title'
        #i18n: true
      - label: 'Draft'
        name: 'draft'
        widget: 'boolean'
        #i18n: 'duplicate'
      - label: 'Author'
        name: 'author'
        widget: 'string'
        #i18n: 'duplicate'
        default: 'Shashi KS'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        #i18n: true
      - label: 'Image'
        name: 'image'
        widget: 'object'
        #i18n: true
        fields:
          - { label: Source, name: src, widget: image } # i18n: 'duplicate'
          - { label: Alt Text, name: alt, widget: string } # i18n: true
      - label: 'Snippet'
        name: 'snippet'
        widget: 'text'
        #i18n: true
      - label: 'Publish Date'
        name: 'publishDate'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:mm'
        #i18n: 'duplicate'
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options: ['Tutorials', 'News', 'Reviews', 'Announcements']
        #i18n: 'duplicate'
      - name: 'body'
        widget: 'markdown'
        label: 'Post Body'
        #i18n: true
